### PR TITLE
Formatted code and fixed 1 'else'-statement

### PR DESCRIPTION
**Pull request by mawoka-myblock**
Yes, that's all! Just some minor formatting and that's it!

### CODE REVIEW

**Comment by argrento** [comment]
Sorry

**Comment by mawoka-myblock** [comment]
Hey @argrento,
I respect your decision to close the pull request, but I'd appreciate a small description why you decided how you decided.

**Comment by argrento** [comment]
Just found that for some reason my message above was truncated.
Fixing messages are good idea, but moving lines 376-377 is not, because that `else` statement is for checking input of the wearable number. If you fix this, you can reopen the PR and I'll merge it.

**Comment by mawoka-myblock** [comment]
> Just found that for some reason my message above was truncated. Fixing messages are good idea, but moving lines 376-377 is not, because that `else` statement is for checking input of the wearable number. If you fix this, you can reopen the PR and I'll merge it.

OK, thank you for your feedback!

**Pull request closed without merging**
